### ISSUE TITLE
Models without id

### ISSUE THREAD

**Issue by cristianfierro** [moritzmorgenroth/ra-data-prisma#2]
My prisma data model looks like this:

`type Investor {
  id: ID! @unique
  firstName: String
  lastName: String
  mailingAddress: Address
  phone: String
}

type Address {
  address: String!
  city: String!
  state: String!
  zip: String!
  country: String!
}`

When trying to fetch the investors the gql looks like this

query investors($where: InvestorWhereInput, $orderBy: InvestorOrderByInput, $skip: Int, $first: Int) {↵  items: investors(where: $where, orderBy: $orderBy, skip: $skip, first: $first) {↵    id↵    firstName↵    lastName↵    **mailingAddress {↵      id↵      __typename↵    }↵**    phone↵    step↵    user {↵      id↵      __typename↵    }↵    investorPreference {↵      id↵      __typename↵    }↵    accreditors {↵      id↵      __typename↵    }↵    __typename↵  }↵  total: investorsConnection(where: $where, orderBy: $orderBy, skip: $skip, first: $first) {↵    aggregate {↵      count↵      __typename↵    }↵    __typename↵  }↵}

but mailingAddress doesn't have an id. Is there a way to set this?

**Comment by moritzmorgenroth** [comment]
Thanks @cristianfierro for your feedback! Should be fixed in [the latest release](https://www.npmjs.com/package/ra-data-prisma). Please upgrade and let me know if it helped!
