### ISSUE TITLE
Problem when creating and changing a post

### ISSUE THREAD

**Issue by KonstantinPatlasov** [moritzmorgenroth/ra-data-prisma#3]
Posts and users are displayed and deleted, but:
When creating a post, an error occurs:

Variable '$author' expected value of type 'UserUpdateOneWithoutPostsInput' but got: {"id":"cjlrmidrk02fz0803mfcqp8q9"}. Reason: 'id' Field 'id' is not defined in the input type 'UserUpdateOneWithoutPostsInput'. 

How to solve this problem?

**Comment by moritzmorgenroth** [comment]
Thanks @konstantin-russia  for your feedback! Should be fixed in [the latest release](https://www.npmjs.com/package/ra-data-prisma). Please upgrade and let me know if it helped!
